#!/usr/bin/env node
/**
 * Derive dashboard data for the Briefing tab from the SHA-256-verified snapshot.
 *
 * Every day shard is integrity-checked against manifest.json BEFORE anything is
 * read from it, so the derived file is trustworthy by construction. The output
 * lives at public/briefing.json (OUTSIDE the signed snapshot directory) and is
 * clearly marked as derived — it is never presented as an upstream artifact.
 *
 * Runs automatically via `npm run prebuild`, so `npm run build` always refreshes
 * it from whatever snapshot is currently present.
 */
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SNAP = join(ROOT, 'public', 'snapshot');

const manifest = JSON.parse(readFileSync(join(SNAP, 'manifest.json'), 'utf8'));

function verifyBytes(buf, expected, label) {
  const hex = createHash('sha256').update(buf).digest('hex');
  if (hex.toLowerCase() !== String(expected).toLowerCase()) {
    throw new Error(`Integrity check failed for ${label}`);
  }
}

const daily = [];
const kev = [];
let shardsVerified = 0;

for (const day of manifest.days) {
  const abs = join(SNAP, day.path);
  const buf = readFileSync(abs);
  verifyBytes(buf, day.sha256, day.path);
  shardsVerified += 1;

  const shard = JSON.parse(buf.toString('utf8'));
  const records = Array.isArray(shard) ? shard : Object.values(shard);

  daily.push({
    date: day.date,
    count: day.count,
    critical: day.critical,
    high: day.high,
    medium: day.medium,
    low: day.low,
    exploited: day.exploited,
  });

  for (const r of records) {
    if (!r.kev) continue;
    kev.push({
      id: r.id,
      title: (r.title ?? '').slice(0, 160),
      score: r.score ?? null,
      sev: r.sev ?? 'unknown',
      vendor: r.kev.vendor ?? null,
      product: r.kev.product ?? null,
      date_added: r.kev.date_added ?? null,
      due_date: r.kev.due_date ?? null,
      ransomware: r.kev.ransomware ?? null,
      published: (r.published ?? '').slice(0, 10),
    });
  }
}

kev.sort((a, b) => String(b.date_added).localeCompare(String(a.date_added)));

const out = {
  _note:
    'Derived at build time from the SHA-256-verified snapshot (manifest + day shards). ' +
    'Not an upstream artifact; regenerated by scripts/derive_briefing.mjs on every prebuild.',
  generated_at: manifest.generated_at,
  last_successful_update: manifest.last_successful_update,
  window: manifest.window,
  complete: manifest.complete,
  totals: manifest.totals,
  coverage: manifest.coverage,
  daily,
  kev,
  kev_count: kev.length,
  sources: manifest.source_status,
  epss: {
    scored_cves: manifest.epss.scored_cves,
    records: manifest.epss.records,
    score_date: manifest.epss.score_date,
  },
  snapshot: {
    shards_verified: shardsVerified,
    search_index_count: manifest.search_index.count,
    shard_map_count: manifest.shard_map.count,
  },
};

writeFileSync(join(ROOT, 'public', 'briefing.json'), JSON.stringify(out));

const days = daily.length;
const peak = daily.reduce((m, d) => (d.count > m.count ? d : m), daily[0]);
console.log(
  `briefing.json written · ${shardsVerified}/${manifest.days.length} shards verified · ` +
    `${days} days · ${kev.length} KEV · peak ${peak.date} (${peak.count})`,
);
if (readdirSync(join(SNAP, 'data')).length === 0) {
  throw new Error('snapshot data dir is empty');
}
